### ISSUE TITLE
npm run mocha fails

### ISSUE THREAD

**Issue by sebastianbenz** [GoogleChrome/gulliver#308]
```
npm run mocha

> gulliver@1.0.0 mocha /Users/sbenz/Documents/projects/gulliver
> _mocha -R  test/**/*

"test/controllers/api.js" reporter blew up with error:
ReferenceError: describe is not defined
    at Object.<anonymous> (/Users/sbenz/Documents/projects/gulliver/test/controllers/api.js:32:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:
...
```

**Comment by juliantoledo** [comment]
Coverage works, but mocha does not.
    "mocha": "node_modules/.bin/_mocha -R  test/**/*"
    "coverage": "node_modules/.bin/istanbul cover node_modules/.bin/_mocha -R  test/**/*"

@ithinkihaveacat any ideas?

**Comment by andreban** [comment]
Running this from the root folder seems to run:
`./node_modules/.bin/mocha test/**/*`

Can you confirm?
